# Generated by Django 3.2.4 on 2021-07-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercrud',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
