# Generated by Django 3.2.4 on 2021-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usercrud_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('profession', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCrud',
        ),
    ]
